spring:
  application:
    name: library
  datasource:
    url: jdbc:mysql://localhost:3306/library_api?createDatabaseIfNotExist=true
    username: root
    password: 12226578
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
